---

- name: Create deployer user
  sudo: true
  user:
    name="{{ user }}"
    comment="{{ user }}"
    shell=/bin/bash
    home={{ home_directory }}
    generate_ssh_key=yes

- name: Setup SSH Authorized Keys
  sudo: true
  sudo_user: "{{ user }}"
  template:
    src=authorized_keys
    dest=~/.ssh/authorized_keys
    mode=600
    owner="{{ user }}"
    group="{{ user }}"

- name: Copy SSH Private Key
  sudo: true
  sudo_user: "{{ user }}"
  template:
    src=../files/deploy_key
    dest=~/.ssh/deploy_key
    mode=600
    owner="{{ user }}"
    group="{{ user }}"

- name: Add Domain SSH Keys to known hosts
  sudo: true
  sudo_user: "{{ user }}"
  shell: >
    ssh-keyscan -H {{ item }} >> ~/.ssh/known_hosts
  with_items: deployer_ssh_keyscan_domains

- name: Create deployer's bashrc
  sudo: true
  sudo_user: "{{ user }}"
  template:
    src=bashrc-user
    dest={{ home_directory }}/.bashrc
    owner="{{ user }}"
    group="{{ user }}"

- name: Create deployer's profile
  sudo: true
  sudo_user: "{{ user }}"
  template:
    src=profile
    dest={{ home_directory }}/.profile
    owner="{{ user }}"
    group="{{ user }}"

- name: "Create deployer's .gemrc"
  sudo: true
  sudo_user: "{{ user }}"
  template:
    src=gemrc
    dest={{ home_directory }}/.gemrc
    owner="{{ user }}"
    group="{{ user }}"

- name: "Create deployer's .bundle"
  sudo: true
  sudo_user: "{{ user }}"
  file:
    state=directory
    path={{ home_directory }}/.bundle
    mode=755
    owner="{{ user }}"
    group="{{ user }}"
